run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - exhaustive

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
  staticcheck:
    checks: ["all", "-SA1019"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA1019:"
  max-issues-per-linter: 50
  max-same-issues: 10
